/**
 * @generated by scripts/materialize-event-membership-functions.mjs
 * do_not_edit: true
 * source_ref: src/data/eventMembership.ts#event-membership-functions
 *
 * Authorization-sensitive membership primitives are copied byte-for-byte from
 * the marked canonical source blocks. Edit that source and re-run this script.
 */

import type {
  MembershipBase,
  MembershipDoc,
  MembershipRole,
  MembershipStatus,
} from '../../src/domainTypes';

/** The collection under an Event that holds its admission records. */
export const MEMBERSHIP_COLLECTION = 'memberships';

/**
 * The envelope version of the shape `readMembership` understands.
 *
 * Follows the versioned-envelope convention `src/eventResolution.ts` uses for
 * its hostname cache (`CACHE_VERSION`) and `cardCache.ts` for its snapshots: a
 * record written by a shape this build does not understand reads as a MISS,
 * never as coerced data.
 *
 * DELIBERATELY NOT AN AUTHORIZATION INPUT — see `admits` below.
 *
 * ANNOTATED, NOT INFERRED (Phase 4b P2 on PR #891). The type annotation is the
 * lockstep with `MembershipBase['schemaVersion']` that the contract's own
 * comment promises. Left inferred, the two `1`s were independent literals: a
 * writer could bump one and type-check, persisting records that AUTHORIZE —
 * `admits()` is version-blind by design — while `readMembership()` rejects
 * every one of them, and no test would fail because the fixtures derive their
 * version from THIS constant. Now a one-sided bump is a compile error.
 */
export const MEMBERSHIP_SCHEMA_VERSION: MembershipBase['schemaVersion'] = 1;

/**
 * The one path builder. Rules, Storage rules, the client, the Functions and the
 * seeds all derive the membership document from `(eventId, uid)` and nothing
 * else, because `storage.rules` can only reach Firestore through
 * `firestore.get()` on a fully-qualified path — it cannot run a query. A shape
 * that needed a lookup (a membership array on the Event doc, a subcollection
 * under `users/{uid}`) would be unreachable from Storage, which is what
 * eliminated those shapes. See specs/event-membership.md § "One get, no query".
 *
 * The document id IS the uid. That is not a convenience; it is the constraint.
 */
export function membershipPath(eventId: string, uid: string): string {
  return `events/${eventId}/${MEMBERSHIP_COLLECTION}/${uid}`;
}

const ROLES: readonly MembershipRole[] = ['member', 'admin'];

/** Role precedence, lowest first. `admin` satisfies a `member` requirement;
 *  `member` does not satisfy an `admin` one. Admin is the ONLY privileged role
 *  today (`CONTEXT.md` § People) — the lattice exists so adding a third role is
 *  a table edit rather than a rewrite of every call site. */
const ROLE_RANK: Record<MembershipRole, number> = { member: 0, admin: 1 };

function isRole(value: unknown): value is MembershipRole {
  return typeof value === 'string' && (ROLES as readonly string[]).includes(value);
}

function isStatus(value: unknown): value is MembershipStatus {
  return value === 'active' || value === 'revoked';
}

/**
 * THE FROZEN CORE of the contract: a record is an admission iff it exists at
 * {@link membershipPath} and its `status` is exactly `'active'`.
 *
 * Deliberately version-BLIND, and deliberately reading one field. Both choices
 * are about keeping the rules transcription honest:
 *
 *  - **Version-blind** because gating authorization on `schemaVersion` would put
 *    a rules deploy in lockstep with every data migration: bump the version,
 *    and every already-written record stops authorizing until the rules catch
 *    up. That is the same deploy-ordering outage the per-Event enforcement
 *    switch exists to prevent, reintroduced one layer down. `status` and the
 *    path are therefore frozen forever; everything else on the document may
 *    version freely.
 *  - **One field** because every clause here is transcribed into
 *    `firestore.rules` AND `storage.rules`, and each costs evaluated
 *    expressions against a 1,000-expression budget the `events/{eventId}` rule
 *    has already blown (#850).
 *
 * Takes the raw document data rather than a parsed `MembershipDoc` precisely
 * BECAUSE rules see raw data. If this took a parsed value it would be testing a
 * different question than the one rules ask.
 */
export function isActiveMembershipData(raw: unknown): boolean {
  if (raw == null || typeof raw !== 'object') return false;
  return (raw as { status?: unknown }).status === 'active';
}

/**
 * The versioned parse, for consumers that need the whole record — the role, the
 * grant provenance, the revocation audit fields. Absent, corrupt, shape-drifted
 * and version-drifted all read as `null`, never as coerced data (ADR 0009's
 * cache convention).
 *
 * A `null` here does NOT mean "not admitted" — see the parity note on
 * {@link admits}. A newer-versioned record still authorizes; this build simply
 * cannot read its extra fields.
 */
export function readMembership(raw: unknown): MembershipDoc | null {
  if (raw == null || typeof raw !== 'object') return null;
  const d = raw as Record<string, unknown>;

  if (d.schemaVersion !== MEMBERSHIP_SCHEMA_VERSION) return null;
  if (typeof d.eventId !== 'string' || d.eventId === '') return null;
  if (typeof d.uid !== 'string' || d.uid === '') return null;
  if (!isRole(d.role)) return null;
  if (!isStatus(d.status)) return null;
  if (typeof d.grantedAt !== 'number' || !Number.isFinite(d.grantedAt)) return null;
  if (typeof d.grantedBy !== 'string' || d.grantedBy === '') return null;
  // `null` is RESERVED for grants with no invitation (provisioner, backfill).
  // An empty string is neither a real invitation id nor that reserved value, so
  // accepting it would record an invitation-backed grant that cannot name the
  // single-use invitation it consumed — losing exactly the provenance #803
  // needs to diagnose reuse (Codex P2 on PR #891).
  if (!(d.invitationId === null || (typeof d.invitationId === 'string' && d.invitationId !== '')))
    return null;

  // Revocation is a PAIR, and its consistency with `status` is part of the
  // shape (Codex P2 on PR #891). A revoked record without usable audit fields
  // has lost the provenance the record exists to carry; an active record still
  // carrying them is a half-applied write. Either way the document is
  // internally inconsistent, and coercing it — silently dropping the unusable
  // half, or retaining a stale one beside `status: 'active'` — hands consumers
  // a "parsed" revocation with no author or date. Read both as a MISS.
  //
  // This is a PARSE decision, never an authorization one: `admits` reads
  // `status` and nothing else, so an inconsistent revoked record still denies
  // and an inconsistent active one still admits, exactly as the rules would.
  // Strictness here can only change what a consumer may READ, never who gets in.
  const revokedAtOk = typeof d.revokedAt === 'number' && Number.isFinite(d.revokedAt);
  const revokedByOk = typeof d.revokedBy === 'string' && d.revokedBy !== '';
  if (d.status === 'revoked' && !(revokedAtOk && revokedByOk)) return null;
  if (d.status === 'active' && (d.revokedAt !== undefined || d.revokedBy !== undefined)) {
    return null;
  }

  const base = {
    schemaVersion: MEMBERSHIP_SCHEMA_VERSION,
    eventId: d.eventId,
    uid: d.uid,
    role: d.role,
    grantedAt: d.grantedAt,
    grantedBy: d.grantedBy,
    invitationId: d.invitationId,
  } as const;

  return d.status === 'revoked'
    ? { ...base, status: 'revoked', revokedAt: d.revokedAt as number, revokedBy: d.revokedBy as string }
    : { ...base, status: 'active' };
}

export function mayAdministerMembership(input: {
  /** The authenticated caller's uid. */
  uid: string | null | undefined;
  /** Whether the uid appears in the LIVE `EventDoc.admins` array. */
  isAdmin: boolean;
  /** Raw data at the CALLER's own {@link membershipPath}. */
  membership: unknown;
}): boolean {
  if (typeof input.uid !== 'string' || input.uid === '') return false;
  if (input.isAdmin !== true) return false;
  return isActiveMembershipData(input.membership);
}
