// Marketing screenshots for nathanpayne.com and blog posts
// (docs/app/marketing-screenshots.md). Not a test: it asserts only enough to
// know the screen it wants is settled. Writes PNGs to artifacts/marketing/.
//
// Run it with `scripts/marketing-shots.sh`, which supplies the emulators and
// the JDK the Firestore emulator needs.
import { test, expect } from '@playwright/test';
import { doc, setDoc } from 'firebase/firestore';
import type { RulesTestEnvironment } from '@firebase/rules-unit-testing';
import { mkdirSync } from 'node:fs';
import path from 'node:path';
import {
  seedHeroEvent,
  renameSignedInPlayer,
  joinHero,
  signedInUid,
  HERO_EVENT_ID,
  HERO_TODAY_INDEX,
  HERO_EDITION,
  clickIfPresent,
  heroDealable,
  HERO_DAY_DEAL,
  PLAYER_NAMES,
  FEED_PROOF_TEXT,
} from './support/fixture';
import { dealBoard, type DealItem } from '../../src/game/logic';
// @ts-expect-error — plain-JS seed script, no type declarations.
import { seedItemDocId } from '../../scripts/seed.mjs';

const OUT_DIR = path.join(process.cwd(), 'artifacts', 'marketing');
const FIXED_SEED = 606060;
/** A partially-marked board: seven claimed squares, no completed line. */
const MARKED = [0, 3, 7, 11, 16, 19, 23];
/** Display name given to the browser's autogenerated account. */
const SIGNED_IN_NAME = 'Alex W.';

let testEnv: RulesTestEnvironment;

/**
 * Take one capture.
 *
 * `animations: 'disabled'` is load-bearing, not tidiness (Codex P2 round 2 on
 * #1020): Playwright's visibility test ignores opacity, so an element that is
 * mid-fade counts as visible and a content assertion alone will happily let the
 * shutter fire during a tab transition — which produced a half-rendered Ranks
 * capture. This finishes CSS transitions and fast-forwards finite animations
 * before the frame is taken, deterministically and without a sleep.
 */
async function shoot(page: import('@playwright/test').Page, name: string): Promise<void> {
  await page.evaluate(() => document.fonts.ready);
  await page.screenshot({
    path: path.join(OUT_DIR, `${HERO_EDITION}-${name}.png`),
    animations: 'disabled',
  });
}

/** Clear every first-open scrim: the analytics notice, the coach overlay, then
 * the reshuffle launch announcement (which only mounts once coach is cleared). */
async function clearScrims(page: import('@playwright/test').Page, firstTimeout: number): Promise<void> {
  await clickIfPresent(page.getByRole('button', { name: /got it/i }), 3_000);
  await clickIfPresent(page.getByRole('button', { name: /deal me in/i }), firstTimeout);
  await clickIfPresent(page.getByRole('button', { name: /let's play/i }), 6_000);
  await clickIfPresent(page.getByRole('button', { name: /got it/i }), 2_000);
  // The warm-up Day's "How this works" banner — in-flow, not a scrim, so it
  // pushes the card off screen until dismissed.
  await clickIfPresent(page.getByRole('button', { name: /dismiss how this works/i }), 4_000);
}

test.use({ viewport: { width: 393, height: 775 } });
test.describe.configure({ timeout: 180_000 });

test.beforeAll(async () => {
  mkdirSync(OUT_DIR, { recursive: true });
  testEnv = await seedHeroEvent();
});

test.afterAll(async () => {
  await testEnv?.cleanup();
});

type SeedItem = { text: string; spicy?: boolean };

async function writeHeroBoard(uid: string): Promise<string[]> {
  // Pool and free-space text both come from the selected Day, so changing
  // HERO_TODAY_INDEX moves the card and its contents together (Codex P2).
  const day = HERO_DAY_DEAL[HERO_TODAY_INDEX];
  // `pool` is left UNSET on each item deliberately: dealBoard reads it to split
  // a main-Day card into its easy and main halves, so tagging every prompt with
  // this Day's pool would leave one half empty and trip the MIN_POOL guard.
  // Absent === 'main', i.e. one undifferentiated pool, which is what dealing a
  // single Day's snapshot means here.
  const pool: DealItem[] = (heroDealable(day.items) as SeedItem[]).map((it) => ({
    id: seedItemDocId(it.text),
    text: it.text,
    spicy: it.spicy === true,
  })) as DealItem[];
  const now = Date.now();
  const cells = dealBoard(pool, day.freeText, FIXED_SEED, 0);
  for (const i of MARKED) {
    cells[i] = { ...cells[i], marked: true, markedAt: now - 2 * 3_600_000 };
  }
  await testEnv.withSecurityRulesDisabled(async (ctx) => {
    await setDoc(
      doc(ctx.firestore(), 'events', HERO_EVENT_ID, 'days', String(HERO_TODAY_INDEX), 'boards', uid),
      { uid, dayIndex: HERO_TODAY_INDEX, seed: FIXED_SEED, createdAt: now - 6 * 3_600_000, cells },
    );
  });
  return cells.map((c) => c.text);
}

test('capture marketing shots', async ({ page }) => {
  await joinHero(page);
  const uid = await signedInUid(page);

  await clearScrims(page, 25_000);

  await expect(page.locator('.grid')).toHaveAttribute('data-server-confirmed', 'true', {
    timeout: 30_000,
  });

  // After the join has written this Player's roster row.
  await renameSignedInPlayer(testEnv, uid, 'Alex W.');

  const cellTexts = await writeHeroBoard(uid);
  await page.reload();
  await expect(page.getByRole('navigation', { name: 'Primary' })).toBeVisible({ timeout: 30_000 });
  await clearScrims(page, 8_000);

  // Wait for the deterministic board (the persistent cache can replay the
  // random first deal on reload).
  await expect
    .poll(async () => (await page.locator('.grid .cell').allTextContents())[0], { timeout: 30_000 })
    .toContain(cellTexts[0]);

  await shoot(page, 'card');

  // Wait for SEEDED CONTENT, never a fixed delay (Codex P2 on #1020). The Feed
  // and Ranks each mount several Firestore subscriptions with explicit loading
  // states; on a cold or loaded machine those outlive any blind timeout, and
  // the harness would then write a "Loading…" / "Tallying the leaderboard…"
  // image and exit 0. A screenshot tool failing loudly beats one succeeding
  // with the wrong picture.
  await renameSignedInPlayer(testEnv, uid, SIGNED_IN_NAME);
  await page.locator('nav.tabs a', { hasText: 'Feed' }).click();
  await expect(page.getByText(FEED_PROOF_TEXT, { exact: false })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByText(/got a BINGO/i).first()).toBeVisible({ timeout: 30_000 });
  await shoot(page, 'feed');

  await renameSignedInPlayer(testEnv, uid, SIGNED_IN_NAME);
  await page.locator('nav.tabs a', { hasText: 'Ranks' }).click();
  // Every seeded player has a row, and this Player's renamed row is the last
  // write to land — so asserting all five means the roster has fully settled.
  for (const name of [...PLAYER_NAMES, SIGNED_IN_NAME]) {
    await expect(page.getByText(name, { exact: false }).first()).toBeVisible({ timeout: 30_000 });
  }
  // Row COUNT as well as row content: every seeded player plus this one.
  await expect(page.locator('.rank')).toHaveCount(PLAYER_NAMES.length + 1, { timeout: 30_000 });
  await shoot(page, 'ranks');
});
