/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.registry-harness.toml --config=wrangler.registry.toml --include-runtime=false --env-interface=RegistryHarnessEnv registry-harness-configuration.d.ts` (hash: f2f606fa61903be7d1322cb401b23015)
interface __BaseEnv_RegistryHarnessEnv {
	REGISTRY: Service<typeof import("./src/registry/registryWorker").RegistryLookupEntrypoint>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/registry/registryHarness");
	}
	interface Env extends __BaseEnv_RegistryHarnessEnv {}
}
interface RegistryHarnessEnv extends __BaseEnv_RegistryHarnessEnv {}
