/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.toml --config=wrangler.registry.toml --include-runtime=false --env-interface=RouterBindings router-configuration.d.ts` (hash: 28c4cd7f4083ee670fe4f0a13571e801)
interface __BaseEnv_RouterBindings {
	ORIGIN_HOST: "fiveacross.web.app";
	ROUTER_VERSION: "v1";
	REGISTRY: Service<typeof import("./src/registry/registryWorker").RegistryLookupEntrypoint>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_RouterBindings {}
}
interface RouterBindings extends __BaseEnv_RouterBindings {}
